// Code generated by tygo. DO NOT EDIT.
/* eslint-disable @typescript-eslint/no-explicit-any */
// Code generated by tygo from api/types/types.go. DO NOT EDIT.
// Regenerate with: make types

//////////
// source: types.go
/*
Package types holds the HTTP wire contract.

This package is the single source of truth for the shapes the frontend sees.
`make types` runs tygo over it to regenerate web/lib/api-types.ts, so a field
rename here becomes a TypeScript compile error there instead of a runtime
surprise during a live webinar.

Keep these boring: scalars, slices, maps and other types from this package.
No interfaces, no generics, no embedded structs from other packages.
*/

/**
 * Role decides what a participant may do inside a room. This is the entire
 * difference between a webinar and a meeting.
 */
export type Role = string;
export const RoleHost: Role = "host";
export const RolePanelist: Role = "panelist";
export const RoleAttendee: Role = "attendee";
export type WebinarStatus = string;
export const StatusScheduled: WebinarStatus = "scheduled";
export const StatusLive: WebinarStatus = "live";
export const StatusEnded: WebinarStatus = "ended";
export const StatusDraft: WebinarStatus = "draft";
export type WebinarKind = string;
export const KindLive: WebinarKind = "live";
export const KindSimulive: WebinarKind = "simulive";
export const KindRecurring: WebinarKind = "recurring";
export type ApprovalMode = string;
export const ApprovalAutomatic: ApprovalMode = "automatic";
export const ApprovalManual: ApprovalMode = "manual";
export type RegistrationState = string;
export const RegApproved: RegistrationState = "approved";
export const RegPending: RegistrationState = "pending";
export const RegDeclined: RegistrationState = "declined";
/**
 * NotificationKind is why somebody is being told something.
 */
export type NotificationKind = string;
/**
 * NotifyApprovalRequested goes to the HOST: somebody is waiting for a decision.
 */
export const NotifyApprovalRequested: NotificationKind = "approval_requested";
/**
 * NotifyRegistrationApproved goes to the REGISTRANT, with their join link.
 */
export const NotifyRegistrationApproved: NotificationKind = "registration_approved";
/**
 * NotifyRegistrationDeclined goes to the REGISTRANT. Sent rather than silently
 * dropped: somebody who registered and hears nothing assumes they are coming.
 */
export const NotifyRegistrationDeclined: NotificationKind = "registration_declined";
/**
 * NotifyRegistrationConfirmed is auto-approve signup: they are in without a host review.
 */
export const NotifyRegistrationConfirmed: NotificationKind = "registration_confirmed";
export const NotifyReminder24h: NotificationKind = "reminder_24h";
export const NotifyReminder1h: NotificationKind = "reminder_1h";
/**
 *  HostAlert is one in-app notification as a host's browser sees it.
 *  *
 *  * Carries the webinar's slug and topic rather than only an id, so the panel can render a
 *  * sentence and a link without a second request per row — a host with twenty alerts would
 *  * otherwise make twenty calls to find out what they were about.
 */
export interface HostAlert {
  id: string;
  kind: NotificationKind;
  webinarId: string; // slug, empty if the webinar is gone
  topic: string;
  subject: string;
  body: string;
  unread: boolean;
  createdAt: string;
}
/**
 * AlertsResponse is the notification panel's payload: the rows plus the badge count,
 * so opening the panel does not need a second request to know what the bell said.
 */
export interface AlertsResponse {
  alerts: HostAlert[];
  unread: number /* int */;
}
/**
 *  ApprovalsRequest is the batch decision: a set of registrations and one state for all of them.
 *  *
 *  * IDs rather than "everyone pending" because a host reviewing forty strangers approves some and
 *  * declines others, and an all-or-nothing endpoint makes them do it one request at a time. An
 *  * empty list is accepted and changes nothing, which is what a host who pressed the button with
 *  * no rows ticked meant.
 */
export interface ApprovalsRequest {
  ids: string[];
  state: RegistrationState;
}
/**
 * ApprovalsResponse reports what actually changed, not what was asked for. The two differ
 * when a row was already in the target state, or belonged to another webinar.
 */
export interface ApprovalsResponse {
  changed: number /* int */;
  notified: number /* int */;
  rows: RegistrantRow[];
}
export interface Person {
  id: string;
  name: string;
  title: string;
  org: string;
  initials: string;
  hue: string;
}
export interface AgendaItem {
  at: string;
  title: string;
  detail?: string;
}
export interface CustomQuestion {
  id: string;
  label: string;
  type: string; // short | select | checkbox
  required: boolean;
  options?: string[];
}
/**
 * WebinarOptions are the things a host decides while scheduling.
 */
export interface WebinarOptions {
  practiceSession: boolean;
  autoRecord: boolean;
  qAndA: boolean;
  /**
   * Polls used to be here, as a checkbox on the scheduling form. It is now
   * PollsEnabled in SessionControls: whether to poll the room is a decision made
   * during the session, next to chat and Q&A, and a host who ticked a box a week
   * earlier still had to be able to change their mind. Old rows keep a stray
   * "polls" key in their options JSON, which unmarshalling ignores.
   */
  attendeeChat: boolean;
  raiseHand: boolean;
  captions: boolean;
  multistream: boolean;
  postWebinarSurvey: boolean;
  /**
   * EmailReminders defaults true for existing rows that never stored the key.
   */
  emailReminders: boolean;
}
/**
 * SessionControls are the things a host flips *during* the session.
 * These live in Postgres rather than in a server's memory: a control has to
 * survive an API restart and it has to apply to someone who joins ten minutes
 * after it was set. "Attendees are hidden" is a property of the session.
 * They are also mirrored into LiveKit room metadata on every change, which is
 * how 500 browsers learn about a toggle without polling.
 */
export interface SessionControls {
  /**
   * HideAttendees is enforced at the SFU: attendee tokens are minted with
   * hidden=true, so an attendee is invisible to every other client rather
   * than merely filtered out of a list by our own JavaScript.
   */
  hideAttendees: boolean;
  muteOnEntry: boolean;
  allowUnmute: boolean;
  chatEnabled: boolean;
  qaEnabled: boolean;
  raiseHandEnabled: boolean;
  reactionsEnabled: boolean;
  /**
   * PollsEnabled decides whether the audience can be polled. Off hides the panel
   * for them entirely; the host still sees theirs, because writing the questions
   * is what you do before turning it on.
   */
  pollsEnabled: boolean;
  /**
   * CaptionsEnabled is the live-caption switch, and it is a CONTROL rather than
   * something the host's own browser remembers. Recognition runs against each
   * speaker's own microphone, so every publisher has to know captions are on or
   * only the person who pressed the button is ever transcribed. Initialised from
   * the scheduled Options.Captions when the webinar is created.
   */
  captionsEnabled: boolean;
  locked: boolean;
  /**
   * ChatDestination decides where an ATTENDEE's chat goes: to the whole room, or
   * to the stage only. The host owns it, which is the point — an attendee picking
   * their own audience is the thing this prevents.
   * It is a control rather than a per-message field so that it is one
   * authoritative value: set by the host through PATCH /controls, stored, and
   * mirrored into SFU room metadata, which is how 500 browsers learn about the
   * change without polling. Messages still carry the destination they were sent
   * with, so switching the setting never rewrites history.
   */
  chatDestination: ChatDestination;
}
/**
 * ChatDestination is the audience for a chat message.
 */
export type ChatDestination = string;
export const ChatToEveryone: ChatDestination = "everyone";
export const ChatToPanelists: ChatDestination = "panelists";
/**
 * ControlsPatch updates a subset of the controls. Pointers so that "not
 * mentioned" and "set to false" are different requests.
 */
export interface ControlsPatch {
  hideAttendees?: boolean;
  muteOnEntry?: boolean;
  allowUnmute?: boolean;
  chatEnabled?: boolean;
  qaEnabled?: boolean;
  raiseHandEnabled?: boolean;
  reactionsEnabled?: boolean;
  pollsEnabled?: boolean;
  captionsEnabled?: boolean;
  locked?: boolean;
  /**
   * A pointer for the same reason as the others: "not mentioned" and "set to
   * everyone" are different requests.
   */
  chatDestination?: ChatDestination;
}
/**
 * PollKind separates a poll from a quiz.
 * A quiz is a poll with a right answer. Same question, same options, same voting
 * and same tally — the only differences are that a quiz records which option is
 * correct and withholds it until voting closes.
 */
export type PollKind = string;
export const PollOpinion: PollKind = "poll";
export const PollQuizKind: PollKind = "quiz";
export type PollState = string;
/**
 * PollDraft is written but never shown to the audience.
 */
export const PollDraft: PollState = "draft";
/**
 * PollOpen is accepting votes. Only one poll per webinar may be open.
 */
export const PollOpen: PollState = "open";
/**
 * PollClosed is final: the tally cannot change and a quiz answer is revealed.
 */
export const PollClosed: PollState = "closed";
/**
 * Poll is one question, as the caller is allowed to see it.
 * "As the caller is allowed to see it" is the important part, and it is the whole
 * reason there are two endpoints rather than one:
 * 	the stage     the tally, the running total, and the correct answer to a quiz.
 * 	the audience  the question and the options. Nothing else.
 * The audience gets no numbers at all — not a per-option count, not a percentage,
 * not even how many people have answered. A live tally is a nudge: someone who has
 * not voted yet can see which way the room is going, and the answers stop being
 * independent. It is withheld by not being SENT, so there is nothing for a client to
 * hide and nothing to read out of a network response.
 */
export interface Poll {
  id: string;
  question: string;
  kind: PollKind;
  options: string[];
  state: PollState;
  createdAt: string;
  closedAt?: string;
  /**
   * CorrectOption is an index into Options, or -1 when there is no right answer
   * or the caller is not yet entitled to know it. Minus one rather than omitted so
   * a client never has to tell "absent" from "index zero".
   * Revealed to the audience once voting closes, unlike the tally: a quiz exists
   * to tell people whether they were right, and by then there is no answer left to
   * influence.
   */
  correctOption: number /* int */;
  /**
   * Votes is a count per option, index-aligned with Options. Empty for the
   * audience, always.
   */
  votes: number /* int */[];
  /**
   * TotalVotes is how many people have answered. Zero for the audience — the
   * presenter needs to know when to move on, and nobody else does.
   */
  totalVotes: number /* int */;
  /**
   * MyChoice is this caller's own answer, or -1 if they have not voted.
   * This is the one number the audience does get, and it is what makes one vote
   * per person visible rather than merely enforced: the inputs are disabled and
   * their answer is shown back to them, and it survives a reload because the vote
   * is keyed on the participant identity we minted rather than on anything the
   * browser is holding.
   */
  myChoice: number /* int */;
}
/**
 * PollInput creates a poll.
 */
export interface PollInput {
  question: string;
  kind: PollKind;
  options: string[];
  /**
   * CorrectOption is required for a quiz and refused for a poll.
   */
  correctOption?: number /* int */;
}
/**
 * PollVoteRequest casts one vote.
 */
export interface PollVoteRequest {
  /**
   * JoinKey authenticates an attendee with no account, as on the realtime relay.
   */
  joinKey?: string;
  /**
   * Choice is an index into the poll's options.
   */
  choice: number /* int */;
}
/**
 * ChatMessageType separates a line of text from an image.
 */
export type ChatMessageType = string;
export const ChatText: ChatMessageType = "text";
export const ChatImage: ChatMessageType = "image";
/**
 * ChatMessage is one persisted line of a session's chat.
 * The field names are the archival contract as much as the wire one: this is what a
 * transcript export contains, and what any later reporting reads. Everything an
 * analytics query needs is on the row — who, when, in which session, to whom, and
 * whether it was words or a picture.
 */
export interface ChatMessage {
  /**
   * ID is the sender's own message id. It is what makes redelivery idempotent: a
   * reconnecting client merges the backlog by id and cannot show a line twice.
   */
  id: string;
  /**
   * Seq is the total order within the session, and the sync cursor. A client asks
   * for everything after the highest one it holds.
   */
  seq: number /* int64 */;
  senderId: string;
  senderName: string;
  senderRole: Role;
  /**
   * UserID is set for a signed-in account and empty for an attendee holding only a
   * join key, which is most of an audience. Present so reporting can join a
   * transcript to accounts where there are accounts to join to.
   */
  userId?: string;
  messageType: ChatMessageType;
  destination: ChatDestination;
  /**
   * Message is the text. Empty for an image.
   */
  message: string;
  /**
   * MediaURL points at this API, not at the storage backend. The handler checks the
   * caller is in this webinar before streaming the bytes; a bucket URL in the payload
   * would be a link that outlives the session and anybody who saw it.
   */
  mediaUrl?: string;
  mediaMime?: string;
  mediaBytes?: number /* int64 */;
  mediaWidth?: number /* int */;
  mediaHeight?: number /* int */;
  timestamp: string;
}
/**
 * ChatBacklog is the answer to "what have I missed".
 * Returned on joining and on every reconnect. `cursor` is the highest seq in the
 * batch, which the client sends back next time — so a reconnect after an hour costs
 * one request and no duplicates.
 */
export interface ChatBacklog {
  messages: ChatMessage[];
  cursor: number /* int64 */;
  /**
   * More reports that the batch was truncated and another read would return further
   * messages. A session with ten thousand lines must not arrive in one response.
   */
  more: boolean;
}
/**
 * ChatImageResponse is returned after an upload. The message has already been created
 * and broadcast by the time this comes back.
 */
export interface ChatImageResponse {
  message: ChatMessage;
}
/**
 * ChatStats is the per-session summary, for reporting.
 */
export interface ChatStats {
  webinarId: string;
  messages: number /* int */;
  images: number /* int */;
  /**
   * Senders is how many distinct people said something — the engagement number,
   * as opposed to how many were in the room.
   */
  senders: number /* int */;
  firstAt?: string;
  lastAt?: string;
  mediaBytes: number /* int64 */;
  toPanelists: number /* int */;
}
/**
 * RoomMessageKind names the realtime messages an attendee may ask the server to
 * deliver for them.
 * The stage-only messages — clearing a raised hand, marking a question answered,
 * asking one person to unmute — are absent on purpose: the host and panelists
 * publish those on the data channel themselves.
 */
export type RoomMessageKind = string;
export const MsgChat: RoomMessageKind = "chat";
export const MsgQuestion: RoomMessageKind = "question";
export const MsgUpvote: RoomMessageKind = "upvote";
export const MsgHand: RoomMessageKind = "hand";
export const MsgReaction: RoomMessageKind = "reaction";
/**
 * SendMessageRequest is one realtime message handed to the server for delivery.
 * Attendee tokens carry canPublishData=false, so the SFU refuses a packet an
 * attendee tries to publish and this endpoint is the only way their chat,
 * questions, hands and reactions reach the room. That is what makes the host's
 * chat destination a rule: the server picks the recipients and stamps the sender,
 * leaving a patched client nothing to lie about.
 * One flat shape rather than a struct per kind, because this contract is
 * generated into TypeScript and four optional fields cost less there than a
 * discriminated union.
 */
export interface SendMessageRequest {
  /**
   * JoinKey authenticates an attendee who registered without an account — the
   * same credential the join endpoint accepts, for the same reason.
   */
  joinKey?: string;
  kind: RoomMessageKind;
  /**
   * ID is the sender's id for this message, echoed in the delivered packet so
   * every client agrees on what to de-duplicate.
   */
  id?: string;
  /**
   * Text is the chat message or the question.
   */
  text?: string;
  /**
   * Anonymous drops the asker's name from a question.
   */
  anonymous?: boolean;
  /**
   * QuestionID is the question being upvoted.
   */
  questionId?: string;
  /**
   * Raised is the new state of this person's hand.
   */
  raised?: boolean;
  /**
   * Emoji is the reaction. Checked against a fixed list server-side, so one
   * patched client cannot push arbitrary strings into 500 people's UI.
   */
  emoji?: string;
  /**
   * Destination is a request, not an instruction, and it is honoured only for the
   * host and the panelists. An attendee's chat goes where the host's setting says
   * regardless of what arrives here — that is the whole point of the endpoint —
   * and the field exists so a panelist who has fallen back to the relay can still
   * address the stage rather than accidentally broadcasting to the audience.
   */
  destination?: ChatDestination;
}
/**
 * SendMessageResponse reports what the server actually did, which is not always
 * what was asked.
 */
export interface SendMessageResponse {
  /**
   * Destination is where a chat message went. For an attendee this is the host's
   * setting rather than anything the client requested, and the composer reads it
   * back so its label can never disagree with what happened.
   */
  destination?: ChatDestination;
  /**
   * Recipients is how many identities the SFU was given. Zero means the whole
   * room, because a broadcast carries no list.
   */
  recipients: number /* int */;
}
export interface WebinarReport {
  attended: number /* int */;
  avgWatchMin: number /* int */;
  questions: number /* int */;
}
export interface AttendanceRow {
  identity: string;
  name: string;
  email?: string;
  watchMin: number /* int */;
}
export interface SessionQuestion {
  id: string;
  identity?: string;
  name: string;
  text: string;
  anonymous?: boolean;
  answered: boolean;
  answer?: string;
  pinned?: boolean;
  dismissed?: boolean;
  upvotes: number /* int */;
  createdAt?: string;
}
export interface QuestionPatch {
  answered?: boolean;
  answer?: string;
  pinned?: boolean;
  dismissed?: boolean;
}
export interface SessionReport {
  registered: number /* int */;
  approved: number /* int */;
  attended: number /* int */;
  avgWatchMin: number /* int */;
  questions: number /* int */;
  pollVoters: number /* int */;
  questionRows: SessionQuestion[];
  attendees: AttendanceRow[];
}
export interface Webinar {
  id: string; // slug, used in URLs
  webinarId: string;
  topic: string;
  summary: string;
  description: string;
  track: string;
  /**
   *  ImageURL is a path back to this API, never a bucket URL — same reasoning as
   * 	 * MediaKey on a chat image, so the backend can move where the bytes live without
   * 	 * breaking a link already on a registration page. Carries a `?v=` that changes
   * 	 * every time the image is replaced, so a cache never serves stale bytes under a
   * 	 * URL that looks unchanged. Empty when no image was uploaded; the frontend falls
   * 	 * back to its own generated cover in that case.
   */
  imageUrl?: string;
  startsAt: string; // RFC3339
  durationMin: number /* int */;
  timeZone: string;
  kind: WebinarKind;
  status: WebinarStatus;
  startedAt?: string;
  endedAt?: string;
  maxDurationMin: number /* int */;
  /**
   * SimuliveRecordingID is the ready recording played as the audience video
   * when Kind is simulive.
   */
  simuliveRecordingId?: string;
  host: Person;
  panelists: Person[];
  agenda: AgendaItem[];
  takeaways: string[];
  registrationRequired: boolean;
  approval: ApprovalMode;
  /**
   *  GuestJoinAllowed decides whether the shared link offers a name-only door.
   * 	 *
   * 	 * DERIVED, not stored, and derived on the SERVER rather than in the browser. It is false
   * 	 * whenever approval is manual, because a guest cannot be approved: there is no address to
   * 	 * write to and nothing for the host to review, so letting one in would walk straight
   * 	 * through the gate the host switched on.
   * 	 *
   * 	 * Sent so the landing page can hide a button rather than offer one that 409s. The endpoint
   * 	 * still checks — see handleGuestJoin — because a hidden button is a courtesy, not a control.
   * 	 * There is deliberately no matching field on WebinarInput: a settable copy would let a
   * 	 * caller ask for a door the approval mode forbids.
   */
  guestJoinAllowed: boolean;
  attendeeLimit: number /* int */;
  registrantCount: number /* int */;
  priceUsd?: number /* int */;
  customQuestions: CustomQuestion[];
  options: WebinarOptions;
  controls: SessionControls;
  /**
   *  The passcode, and who is allowed to see it.
   * 	 *
   * 	 * A shared secret the host hands out separately from the link, so it must only ever
   * 	 * reach the host's own views. It was being serialised into two unauthenticated
   * 	 * endpoints — the browse list and the public webinar page — which meant anybody could
   * 	 * read it off the API and walk straight past the gate it exists to be.
   * 	 *
   * 	 * publicWebinar in the api package is what strips it. PasscodeRequired is what
   * 	 * replaces it, because the registration form still has to know whether to ask.
   */
  passcode?: string;
  passcodeRequired: boolean;
  /**
   *  SFUProject is which LiveKit project this webinar's room lives on, once chosen.
   * 	 *
   * 	 * Empty until the first join picks one. Operator information — it is what answers "which
   * 	 * of my LiveKit accounts is this session billing against" and "what is still running on
   * 	 * the project I want to retire" — so it reaches the host's own views and is stripped by
   * 	 * publicWebinar, exactly like the passcode.
   * 	 *
   * 	 * Not stripped because it is a secret; a project id is not. Stripped because the audience
   * 	 * has no use for it and every field that reaches an unauthenticated endpoint is a field
   * 	 * somebody has to think about again later.
   */
  sfuProject?: string;
  report?: WebinarReport;
}
/**
 * WebinarInput creates or replaces a webinar. PATCH has replace semantics
 * rather than merge: the schedule form always holds the whole record, and
 * merge semantics on a nested shape like Agenda is where partial-update bugs
 * come from.
 */
export interface WebinarInput {
  topic: string;
  summary: string;
  description: string;
  track: string;
  startsAt: string; // RFC3339, absolute instant
  durationMin: number /* int */;
  timeZone: string; // IANA name, for display
  kind: WebinarKind;
  status: WebinarStatus; // scheduled | draft only
  simuliveRecordingId?: string;
  registrationRequired: boolean;
  approval: ApprovalMode;
  /**
   * No GuestJoinAllowed here. This is the request type for creating a webinar, and the flag
   * is derived from Approval on read — a settable copy would let a caller ask for a door the
   * approval mode forbids.
   */
  attendeeLimit: number /* int */;
  passcode: string;
  agenda: AgendaItem[];
  takeaways: string[];
  customQuestions: CustomQuestion[];
  panelistEmails: string[];
  options: WebinarOptions;
  controls: SessionControls;
}
/**
 * Account is the signed-in person. Hosting is a capability on an ordinary
 * account, not a separate kind of account: the same person registers for other
 * people's webinars and runs their own.
 */
export interface Account {
  id: string;
  email: string;
  name: string;
  title: string;
  org: string;
  /**
   * Phone is E.164 shape (`+` then digits), same convention as
   * Registration.Phone — the caller's own number, never shown to anyone
   * else (not on Person, the type other attendees/panelists see).
   */
  phone: string;
  initials: string;
  hue: string;
  /**
   * CanHost is GRANTED by an admin. It was once a checkbox on the signup form; see
   * migrations/0011 for why that had to stop.
   */
  canHost: boolean;
  /**
   * IsAdmin may grant CanHost to others. Set only from ADMIN_EMAILS at boot — there is no
   * endpoint that promotes an admin, deliberately, because a privilege grantable in-band is
   * grantable by whoever takes over one account.
   */
  isAdmin: boolean;
  /**
   * MaxDurationMin is an optional custom maximum meeting duration in minutes for this user.
   * NULL means use the system default (e.g. 180 min = 3 hours).
   */
  maxDurationMin?: number /* int */;
  /**
   * CanCdnBroadcast allows this host's webinars to broadcast to audience via CDN HLS.
   */
  canCdnBroadcast: boolean;
}
export interface SignupRequest {
  name: string;
  email: string;
  password: string;
  org?: string;
  title?: string;
  /**
   * Phone is E.164 shape, same as Registration.Phone — see validateSignup
   * for the shape check and store.normalisePhone for how it's stored.
   */
  phone?: string;
  /**
   *  WantsHost is ACCEPTED AND IGNORED, and the field is kept for exactly that reason.
   * 	 *
   * 	 * Every new account gets hosting automatically now (see handleSignup) — nothing left to
   * 	 * ask for. Removing the field outright would make an older cached bundle's signup fail
   * 	 * on an unknown-field error, since this API rejects unknown fields, so the request still
   * 	 * parses and the value no longer does anything either way.
   */
  wantsHost: boolean;
}
/**
 * HostGrant is an admin's decision about one account's hosting capability —
 * still the only way to take it away from an account after signup.
 */
export interface HostGrant {
  canHost: boolean;
}
/**
 * CdnBroadcastGrant is an admin's grant allowing a host account to use CDN broadcast mode.
 */
export interface CdnBroadcastGrant {
  canCdnBroadcast: boolean;
}
/**
 *  AdminUser is one row of the admin panel.
 *  *
 *  * Carries what an admin needs to decide whether this person should be able to run webinars —
 *  * who they are, when they joined, whether they asked — and nothing more. No password hash, no
 *  * session data, and no registration history: the panel's job is granting a capability, not
 *  * profiling users.
 */
export interface AdminUser {
  id: string;
  email: string;
  name: string;
  title?: string;
  org?: string;
  initials: string;
  hue: string;
  canHost: boolean;
  isAdmin: boolean;
  createdAt: string;
  /**
   * WebinarCount is why revoking is not always safe: an account that owns scheduled
   * sessions still needs to be able to start them.
   */
  webinarCount: number /* int */;
  /**
   * MaxDurationMin is an optional custom maximum meeting duration in minutes configured by an admin.
   */
  maxDurationMin?: number /* int */;
  /**
   * CanCdnBroadcast reports whether this user is enabled for CDN broadcast webinars.
   */
  canCdnBroadcast: boolean;
}
export interface LoginRequest {
  email: string;
  password: string;
}
/**
 *  SupabaseAuthRequest exchanges a verified Supabase Auth access token for this
 *  * app's webcast_session cookie.
 *  *
 *  * The browser completes Google (or other) OAuth with Supabase JS; this body is
 *  * what arrives after that redirect. The API never talks to Google directly —
 *  * it only verifies Supabase's JWT and links or creates a local users row.
 */
export interface SupabaseAuthRequest {
  accessToken: string;
}
export interface ProfilePatch {
  name?: string;
  title?: string;
  org?: string;
  phone?: string;
  /**
   * WantsHost is accepted and ignored, for the same reason as on SignupRequest: an older
   * bundle still submitting the old profile form must be able to save the name change it
   * was really for. store.UpdateProfile no longer touches can_host.
   */
  wantsHost?: boolean;
}
export interface RegisterRequest {
  firstName: string;
  lastName: string;
  email: string;
  company?: string;
  jobTitle?: string;
  country?: string;
  /**
   * * The mobile number in E.164 shape — `+` then digits, no spaces. The form assembles it
   * 	 *  from a dial-code picker and a national number; the wire carries one value, because a
   * 	 *  number split across two fields is a property of the form and not of the number.
   */
  phone?: string;
  answers?: { [key: string]: string};
  consent: boolean;
  /**
   * * The webinar's passcode, when it has one. Checked at registration, which is the
   * 	 *  one gate every attendee passes through — a join key is only issued here.
   */
  passcode?: string;
}
export interface Registration {
  id?: string;
  webinarId: string; // slug
  email: string;
  firstName: string;
  lastName: string;
  company?: string;
  jobTitle?: string;
  country?: string;
  phone?: string;
  /**
   *  IsGuest: entered by name only, through the guest door. No email was collected, so this
   * 	 * row is not a lead and the host's registrant list marks it as such rather than showing a
   * 	 * blank address that looks like a bug.
   */
  isGuest?: boolean;
  answers?: { [key: string]: string};
  state: RegistrationState;
  joinKey: string;
  registeredAt: string;
}
/**
 * RegisteredWebinar is one row of "My webinars" for a signed-in account: the
 * registration plus the webinar it is for, so the page needs one request rather
 * than the whole catalogue plus a filter.
 */
export interface RegisteredWebinar {
  webinar: Webinar;
  registration: Registration;
}
/**
 * LookupRequest resolves the join keys a browser is holding back into
 * registrations. Registering without an account is still supported — the join
 * key is the credential, exactly like the personal link Zoom emails out.
 */
export interface LookupRequest {
  joinKeys: string[];
}
/**
 *  GuestJoinRequest is the whole guest form: one field.
 *  *
 *  * No email, deliberately. Asking for one and not verifying it produces a lead list full of
 *  * a@a.com, and asking for one at all is the friction this door exists to remove. A host who
 *  * wants addresses turns approval on, or points people at Register & Join.
 */
export interface GuestJoinRequest {
  name: string;
}
export interface JoinRequest {
  /**
   * JoinKey is optional for a signed-in account: the server finds the
   * registration from the session instead.
   */
  joinKey?: string;
}
/**
 * JoinResponse is what the browser hands to the LiveKit client SDK.
 */
export interface JoinResponse {
  token: string;
  url: string;
  room: string;
  role: Role;
  identity: string;
  displayName: string;
  /**
   * CanPublish is echoed so the UI can render the right controls without
   * having to decode the JWT.
   */
  canPublish: boolean;
  /**
   * Controls is the session state at join time. Later changes arrive over
   * LiveKit room metadata rather than by polling this endpoint.
   */
  controls: SessionControls;
  topic: string;
  /**
   *  StartedAt is when the host took the webinar live (RFC3339).
   * 	 *
   * 	 * The room header clock counts from this, not from the browser's connect
   * 	 * time — a late joiner must see the same elapsed time as everyone else.
   * 	 * Empty only if the session has somehow not been stamped live yet.
   */
  startedAt?: string;
  /**
   *  EndedAt is when the host ended the session (RFC3339). Present so a client
   * 	 * that still holds a connection can freeze the elapsed clock on the final
   * 	 * duration rather than keep ticking.
   */
  endedAt?: string;
  /**
   * Hidden reports that the SFU will keep this participant invisible to the
   * other participants. Shown to attendees so the privacy claim is legible.
   */
  hidden: boolean;
  /**
   *  CanRecord answers whether this ACCOUNT may see the record control at all,
   * 	 * decided by the server rather than inferred from the role.
   * 	 *
   * 	 * It is NOT the same as CanPublish. The recording endpoints sit behind
   * 	 * requireStage, which wants an ACCOUNT on this webinar's stage roster — the
   * 	 * host, or a name on the panelist list. An attendee the host promoted
   * 	 * publishes exactly like a panelist and has no account at all, so inferring
   * 	 * this from publish permission offered them a button whose every request came
   * 	 * back 401.
   * 	 *
   * 	 * Deliberately NOT gated on whether the instance has recording storage
   * 	 * configured any more — that used to fold into this field, which hid the
   * 	 * button outright on an instance with RECORDINGS_ENABLED=false, even though
   * 	 * local, on-device recording needs no server storage at all. See
   * 	 * AppConfig.CloudRecordingEnabled for that half of the question; the record
   * 	 * control combines both to decide which destinations to offer.
   */
  canRecord: boolean;
  /**
   *  JoinKey is the caller's own registration key, echoed back.
   * 	 *
   * 	 * For the guest door it is the point of the response: a guest has no account and no
   * 	 * emailed link, so this string is the only thing that gets them back into the room after
   * 	 * a reload, and the browser stores it exactly as a registrant's is stored.
   * 	 *
   * 	 * Echoed on the registered path too, where it is harmless — the caller either just sent
   * 	 * it or holds a session that owns the registration. Empty for a host or panelist, who
   * 	 * join on their account and have no registration at all.
   */
  joinKey?: string;
  /**
   * MaxDurationMin is the maximum allowed duration for this session in minutes.
   */
  maxDurationMin: number /* int */;
  /**
   * CdnBroadcast is true when this webinar's *audience* is on the mixed
   * program (WHEP live, HLS/file for simulive), including for a promoted
   * attendee — so demote can put them back on the mix player.
   * CdnStreamURL is what to play; set whenever the webinar is in that mode
   * so a demote remount still has a URL.
   */
  cdnBroadcast?: boolean;
  cdnStreamUrl?: string;
  /**
   * CdnLowLatency is true when CdnStreamURL is the live origin (WHEP),
   * so the player can sit close to the live edge. False for simulive.
   */
  cdnLowLatency?: boolean;
}
export interface SetUserMaxDurationRequest {
  maxDurationMin?: number /* int */;
}
/**
 * RoomMeta is mirrored into LiveKit room metadata on every control change.
 * It is how one host action reaches 500 browsers: the SFU pushes metadata down
 * the signalling connection every client already holds open, so nobody polls.
 * Public to the room by design — it carries no personal data.
 */
export interface RoomMeta {
  controls: SessionControls;
  status: WebinarStatus;
  topic: string;
  /**
   *  StartedAt / EndedAt mirror the webinar row so every connected client can
   * 	 * drive the same elapsed clock without a second HTTP round trip.
   */
  startedAt?: string;
  endedAt?: string;
  /**
   * Recording is broadcast to every client rather than known only to the person
   * who pressed the button. Being recorded without being told is the kind of
   * thing people sue over, so the indicator has to come from the server and
   * reach the whole room.
   */
  recording: boolean;
  /**
   * MaxDurationMin is the maximum allowed duration for this session in minutes.
   */
  maxDurationMin?: number /* int */;
}
export type RecordingStatus = string;
export const RecordingActive: RecordingStatus = "recording";
export const RecordingProcessing: RecordingStatus = "processing";
export const RecordingReady: RecordingStatus = "ready";
export const RecordingFailed: RecordingStatus = "failed";
/**
 * Recording is one captured session.
 * The bytes live in object storage; this is everything needed to list, play and
 * account for them without touching the storage backend.
 */
export interface Recording {
  id: string;
  webinar: string; // slug
  topic: string;
  status: RecordingStatus;
  /**
   * Mime is the container the recording browser actually produced — Safari
   * records MP4, Chrome records WebM — so it cannot be assumed on the way out.
   */
  mime: string;
  sizeBytes: number /* int64 */;
  durationMs: number /* int64 */;
  startedBy: string;
  createdAt: string;
  stoppedAt?: string;
  /**
   * Ext is the file extension for the download name, derived from Mime by the
   * server so no client has to parse codec strings.
   */
  ext: string;
  egressId?: string;
  isPublic: boolean;
  passcode?: string;
  passcodeRequired: boolean;
  uploadedToS3: boolean;
  uploadPercent: number /* int */;
  /**
   * RetentionDays is how long cloud recordings are kept (from createdAt).
   * 0 means the instance does not auto-delete.
   */
  retentionDays: number /* int */;
  /**
   * ExpiresAt is when this file will be deleted from cloud storage, RFC3339.
   * Empty when retention is disabled or createdAt could not be parsed.
   */
  expiresAt?: string;
  /**
   * Parts is every take in this session, oldest first. Stop-then-record-again
   * appends a part rather than listing a second recording. A session with a
   * single take still has one entry, so the player does not have to special-case
   * the shape.
   */
  parts?: RecordingPart[];
}
/**
 * RecordingPart is one start/stop take inside a session. The bytes are a
 * finished file; the session is the thing a host plays, shares and deletes.
 */
export interface RecordingPart {
  id: string;
  status: RecordingStatus;
  sizeBytes: number /* int64 */;
  durationMs: number /* int64 */;
  createdAt: string;
}
/**
 * StartRecordingRequest is sent by the browser that will do the capturing. It
 * names the container it can produce, because that differs by browser and the
 * server has to store what it is actually given.
 */
export interface StartRecordingRequest {
  mime: string;
}
/**
 * ShareRecordingRequest is sent by the host to configure public access and passcode.
 */
export interface ShareRecordingRequest {
  isPublic?: boolean;
  passcode?: string;
}
/**
 * PublicRecording is the sanitized recording metadata returned to anonymous viewers.
 */
export interface PublicRecording {
  id: string;
  webinar: string;
  topic: string;
  status: RecordingStatus;
  hostName: string;
  durationMs: number /* int64 */;
  sizeBytes: number /* int64 */;
  createdAt: string;
  ext: string;
  passcodeRequired: boolean;
  unlocked: boolean;
  uploadedToS3: boolean;
  uploadPercent: number /* int */;
  retentionDays: number /* int */;
  expiresAt?: string;
  parts?: RecordingPart[];
}
/**
 * LiveParticipant is one row of the host's participant panel.
 * This comes from LiveKit's *server* API, not from the host's browser, which
 * matters: hidden attendees are excluded from client-side rosters by design, so
 * the host would otherwise be unable to moderate the people they have hidden.
 */
export interface LiveParticipant {
  identity: string;
  name: string;
  role: Role;
  joinedAt: string;
  publishing: string[];
  audioMuted: boolean;
  hidden: boolean;
  canPublish: boolean;
  /**
   * CanSpeak reports a microphone grant specifically, so the host's panel can
   * tell "allowed to speak" apart from "on the stage with a camera".
   */
  canSpeak: boolean;
  /**
   * AudioOnly is the scope the host granted, read back from what we minted —
   * not inferred from what they happen to be publishing. A full panelist with
   * their camera off is not the same as somebody allowed only to speak, and
   * guessing from the track list conflates the two.
   */
  audioOnly: boolean;
  /**
   * MutedByHost is the difference between "not a speaker" and "a speaker the
   * host silenced". Both have CanSpeak false, and the host's panel has to offer
   * "allow to speak again" for the second one rather than treating them as
   * audience.
   */
  mutedByHost: boolean;
  /**
   * CoHost is a panelist the host made their equal: full moderation rights,
   * not just a stage seat. See lk.Spec.CoHost.
   */
  coHost: boolean;
}
export interface LiveRoom {
  room: string;
  status: WebinarStatus;
  controls: SessionControls;
  participants: LiveParticipant[];
  attendees: number /* int */;
  onStage: number /* int */;
}
export interface MutePatch {
  muted: boolean;
}
/**
 * StageRequest promotes an attendee onto the stage or sends them back.
 */
export interface StageRequest {
  role: Role; // panelist | attendee
  /**
   * AudioOnly is "allow to speak": the attendee gets a microphone and a screen
   * share, but no camera.
   * This is the common case by far. A host taking a question wants to hear one
   * person, not hand them the stage, and a full promotion means an unprepared
   * attendee's camera and desktop are one click from 500 people.
   */
  audioOnly: boolean;
}
export interface MuteAllResponse {
  muted: number /* int */;
}
/**
 * StageAllResponse reports a bulk allow-all-to-speak or revoke-all-speaking
 * action — how many attendees it actually applied to, the same shape as
 * MuteAllResponse and for the same reason: a host clicking a bulk action on
 * an empty or already-settled room needs to see that nothing silently
 * failed, not just a bare 200.
 */
export interface StageAllResponse {
  count: number /* int */;
}
export interface RegistrantRow {
  id: string;
  name: string;
  email: string;
  company?: string;
  jobTitle?: string;
  phone?: string;
  state: RegistrationState;
  createdAt: string;
  hasAccount: boolean;
  /**
   *  IsGuest marks a row that came through the name-only door.
   * 	 *
   * 	 * Surfaced to the host because the alternative is an empty Email cell that reads as a
   * 	 * bug in the export. It is also the honest answer to "why can I not follow this person
   * 	 * up": nothing was collected, by design.
   */
  isGuest?: boolean;
}
export interface PanelistRequest {
  email: string;
}
/**
 * CoHostPatch turns a panelist into a second, equal moderator for this run of
 * the webinar, or turns them back into an ordinary panelist. See
 * lk.Spec.CoHost for exactly what that grants and withholds.
 */
export interface CoHostPatch {
  coHost: boolean;
}
/**
 * TransferHostRequest hands the webinar to another panelist already in the room.
 * Identity is their LiveKit identity (user_<id>). The caller remains a panelist so
 * they can rejoin the stage later; the target becomes the owner for every host
 * endpoint that checks ownership. Publish grants are restored on handoff, so a
 * muted panelist (CanPublish false) is still a valid target.
 */
export interface TransferHostRequest {
  identity: string;
}
/**
 * AppConfig is public, unauthenticated, and read once by the frontend at boot.
 * It exists so the UI has no build-time constants for things an operator sets:
 * the product name, the public URL used to build share links, the attendee
 * ceiling shown next to the seat count.
 */
export interface AppConfig {
  appName: string;
  webBaseUrl: string;
  supportEmail?: string;
  maxAttendees: number /* int */;
  signupOpen: boolean;
  /**
   * DefaultMaxMeetingMin is the system default maximum meeting duration in minutes (default 180 = 3h).
   */
  defaultMaxMeetingMin: number /* int */;
  /**
   * Tracks are the topic tags already in use, offered as suggestions rather
   * than a fixed enum so an operator never has to edit a list in the bundle.
   */
  tracks: string[];
  /**
   * GoogleClientID and GoogleAPIKey turn on the Google Drive source in the
   * share-a-file picker. Both are public values — see config.Config — and both
   * are empty unless an operator sets them, which the picker reports as "not
   * configured" rather than failing on click.
   */
  googleClientId?: string;
  googleApiKey?: string;
  /**
   *  Supabase Auth (Google sign-in). Public values only — the JWT secret stays
   * 	 * on the API. When googleAuth is false the Continue with Google button is hidden.
   * 	 *
   * 	 * Distinct from GoogleClientID above: that pair is Drive Picker, not login.
   */
  supabaseUrl?: string;
  supabaseAnonKey?: string;
  googleAuth?: boolean;
  /**
   *  CloudRecordingEnabled is whether this instance has object storage for
   * 	 * recordings at all (RECORDINGS_ENABLED). Separate from JoinResponse.CanRecord,
   * 	 * which is about the ACCOUNT (host or panelist); this is about the INSTANCE.
   * 	 * The record control uses it to decide whether to offer "the cloud" as a
   * 	 * destination at all, rather than offering a button that always 503s — local,
   * 	 * on-device recording (see web/lib/local-recording.ts) needs neither this nor
   * 	 * the server's storage, so it is unaffected by it either way.
   */
  cloudRecordingEnabled: boolean;
  recordingMode?: string;
  /**
   * RecordingsRetentionDays is how long cloud recordings are kept before
   * automatic deletion. 0 means they are kept until a host deletes them.
   */
  recordingsRetentionDays: number /* int */;
  /**
   * EmailConfigured is whether SMTP can actually deliver. The UI uses it to
   * say "we'll email you" vs "save this join link; mail is off".
   */
  emailConfigured: boolean;
  /**
   * TelemetryEnabled mirrors config.Config.TelemetryEnabled: whether POST
   * /telemetry accepts anything. The frontend's telemetry poller checks this
   * before attaching a single listener or sampling a single stat, so turning
   * the flag off also turns off the client-side work, not just the endpoint.
   */
  telemetryEnabled?: boolean;
}
/**
 *  TelemetryEvent is one entry in a POST /telemetry batch — the shape is
 *  * intentionally loose (Payload is a bag of whatever the client measured)
 *  * because this is a temporary diagnostic path for one test window, not a
 *  * contract anything else in the app depends on. See handleTelemetry.
 */
export interface TelemetryEvent {
  event: string;
  timestamp: number /* int64 */; // epoch ms, client clock
  payload?: { [key: string]: any};
}
export interface APIError {
  error: string;
  message: string;
  fields?: { [key: string]: string};
}
export interface StatusResponse {
  status: string;
}
