-- Bots: the only part of this CRM that talks back.
--
-- Reminders, broadcasts and drips all send outwards on a clock. A bot is the other
-- direction: somebody writes to the host's number and something answers within the
-- second, because Meta's 24-hour service window is open exactly then and free-form
-- text is allowed exactly then. That is why nothing in this file goes through the
-- `notifications` outbox — a reply that arrives thirty seconds later, in the order a
-- sweep happened to read its rows, is not a conversation. The one thing the sweeper
-- does own is a flow that asked to pause (see crm_bot_sessions.resume_at).
--
-- Three tables, and the split is the same one the drips made:
--
--   crm_bots          the rule: which messages it answers, and whether it is on.
--   crm_bot_nodes     the flow: what it says, what it asks, where each answer goes.
--   crm_bot_sessions  one person's place in it.
--
-- The flow is a graph and it is stored as one — nodes keyed by name, edges as those
-- names — rather than as a blob of JSON on the bot. Two reasons. An `enroll` node
-- points at a real drip, and a foreign key is the only thing that keeps that pointer
-- honest when the sequence is deleted. And a session has to name where it is: a key
-- into a table survives an edit that a position in a JSON array does not.

CREATE TABLE crm_bots (
    id      uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    host_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,

    -- The host's label, for their own list. Never sent to anybody.
    name    text NOT NULL,

    /* Which inbound messages start it.
     *
     *   any_message  anything at all from somebody the bot is not already talking to.
     *   keyword      only when the message is one of `keywords`.
     *
     * Two, on purpose. Everything else a trigger could plausibly key on — a button on
     * a template, a referral ad, an order — is a message this server would still have
     * to match on its text, so it is the keyword case with extra words for it.
     */
    trigger_kind text NOT NULL CHECK (trigger_kind IN ('any_message','keyword')),

    /* The words that start a keyword bot, already lower-cased by the API.
     *
     * Matched against the whole message rather than as a substring, the same rule
     * isWhatsAppStop uses and for the same reason: "I do not want the price list" is
     * not a request for the price list.
     */
    keywords text[] NOT NULL DEFAULT '{}',

    -- Where a new conversation starts. A key into crm_bot_nodes, checked by the API
    -- rather than by a foreign key: the bot row and its nodes are written in one
    -- transaction, so a constraint here would have to be deferred to be satisfiable.
    entry_key text NOT NULL DEFAULT '',

    -- Off unless the host says otherwise. A bot is the one feature here that answers
    -- strangers without anybody reading what it says first.
    active  boolean NOT NULL DEFAULT false,

    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX crm_bots_host_idx ON crm_bots (host_id, created_at DESC);
-- The runtime's own query: this host's live bots, keywords first.
CREATE INDEX crm_bots_live_idx ON crm_bots (host_id) WHERE active;

/* At most one bot answering everything.
 *
 * Two catch-alls would both match every message and the winner would be whichever
 * the planner returned first — a coin toss the host cannot see, decided again on
 * every message. Keyword bots may overlap freely: the words are the host's own
 * choice and the first match wins in a defined order.
 */
CREATE UNIQUE INDEX crm_bots_one_catch_all
    ON crm_bots (host_id) WHERE active AND trigger_kind = 'any_message';

CREATE TABLE crm_bot_nodes (
    bot_id uuid NOT NULL REFERENCES crm_bots(id) ON DELETE CASCADE,

    /* The node's name inside this bot, and half its primary key.
     *
     * A name rather than a uuid because it is what every edge in the flow is written
     * as, and because a session stores one: reading `node_key = 'price'` out of a
     * stuck conversation is worth more than reading a uuid. Generated by the builder,
     * never shown to the person being messaged.
     */
    key    text NOT NULL CHECK (key <> '' AND length(key) <= 64),

    /* What this step does.
     *
     *   message  say something and carry on.
     *   ask      say something with up to three buttons, and wait for the answer.
     *   wait     pause, then carry on — the only node the sweeper has to wake.
     *   enroll   put them on a drip sequence, and carry on.
     *   handoff  stop, and hand the conversation to a person.
     *
     * The plan also listed `condition` and `set tag`. A tag is a thing contacts still
     * do not have. A condition over what — there are no variables in this flow beyond
     * the answer somebody just gave, and that answer is what `ask` already branches
     * on, so a second node for it would be a second way to write the same edge.
     */
    kind   text NOT NULL CHECK (kind IN ('message','ask','wait','enroll','handoff')),

    -- What it says. Required for message and ask; optional for handoff (the sentence
    -- before a human takes over); unused by wait and enroll.
    text   text NOT NULL DEFAULT '',

    /* An ask's buttons: [{"label":"Yes","next":"price"}], up to three.
     *
     * Meta's own limit on interactive reply buttons is three, with 20 characters of
     * label each, so it is also the limit on how many ways a question can branch.
     * Stored with the node rather than as rows: a button has no identity apart from
     * its position in the question, and nothing ever points at one.
     */
    options jsonb NOT NULL DEFAULT '[]'::jsonb,

    /* Where to go when this node is finished, or '' to stop there.
     *
     * For an `ask` this is the fallback — where an answer that matched no button goes.
     * Empty on an ask means "hand it to a person", which is the conservative reading
     * of a bot that did not understand somebody.
     */
    next_key text NOT NULL DEFAULT '',

    -- How long a `wait` pauses for. Capped at 24 hours because that is Meta's service
    -- window: a flow that sleeps longer than the window wakes up unable to speak.
    delay_minutes integer NOT NULL DEFAULT 0
        CHECK (delay_minutes >= 0 AND delay_minutes <= 1440),

    /* Which sequence an `enroll` node puts them on.
     *
     * SET NULL rather than CASCADE: deleting a sequence must not silently delete a
     * step out of the middle of a running flow. The node survives with nothing to
     * enrol anybody on, the runtime steps over it, and the builder shows it as broken
     * — which is the state the host is actually in.
     */
    drip_id uuid REFERENCES crm_drips(id) ON DELETE SET NULL,

    -- The builder's own ordering, so a saved flow reads back in the order it was
    -- written. Not the flow: the edges are the flow.
    position integer NOT NULL DEFAULT 0,

    PRIMARY KEY (bot_id, key)
);

CREATE TABLE crm_bot_sessions (
    id         uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    bot_id     uuid NOT NULL REFERENCES crm_bots(id) ON DELETE CASCADE,
    contact_id uuid NOT NULL REFERENCES crm_contacts(id) ON DELETE CASCADE,

    -- Where this conversation is: the ask it is waiting at, or the node to run next
    -- when it wakes. Not a foreign key — a node the host has since deleted has to
    -- read as "that step is gone" rather than prevent the edit.
    node_key   text NOT NULL DEFAULT '',

    /* waiting   the bot has asked something and is waiting for an answer.
     * sleeping  a wait node is holding it; resume_at says until when.
     * done      the flow ran out of steps.
     * handoff   a person has it now. See crm_contacts.bot_paused_at.
     * stopped   it ended for a reason nobody chose — the window closed, the step it
     *           was standing on was deleted, it ran too long. ended_reason says.
     */
    state      text NOT NULL DEFAULT 'waiting'
        CHECK (state IN ('waiting','sleeping','done','handoff','stopped')),
    ended_reason text NOT NULL DEFAULT '',

    resume_at  timestamptz,

    /* The inbound message this session last acted on.
     *
     * Meta retries any delivery it did not see a 2xx for, including one that was
     * processed by an instance that then fell over. Without this, the retry of the
     * answer to a question is read as a second answer, and the flow runs twice — two
     * messages to one person, out of one of theirs. The wamid is the only thing in the
     * payload that identifies the message, so it is what is remembered.
     */
    last_wamid text NOT NULL DEFAULT '',

    -- Nodes run in this conversation, ever. The bound on a flow that loops: a cycle
    -- is refused at save time, but an edit while somebody is mid-flow can still make
    -- one, and that must cost a bounded number of messages rather than a bill.
    steps      integer NOT NULL DEFAULT 0,

    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

/* One live conversation per contact, across every bot.
 *
 * A person talking to a business is in one conversation, not one per bot: without
 * this, a keyword that matches while another flow is mid-question starts a second
 * flow and the two take turns replying to the same messages. Finished sessions are
 * kept — "who has been through this, and where did they stop" is most of what the
 * bot screen is for — and they are what the retry guard above reads.
 */
CREATE UNIQUE INDEX crm_bot_one_live_per_contact
    ON crm_bot_sessions (contact_id) WHERE state IN ('waiting','sleeping');

-- The sweep: sleeping sessions that are due.
CREATE INDEX crm_bot_sessions_resume_idx
    ON crm_bot_sessions (resume_at) WHERE state = 'sleeping';
CREATE INDEX crm_bot_sessions_bot_idx ON crm_bot_sessions (bot_id, created_at DESC);
CREATE INDEX crm_bot_sessions_contact_idx ON crm_bot_sessions (contact_id, created_at DESC);

/* When a person took the conversation over from the bot.
 *
 * On the contact rather than on the session, because it outlives any one session:
 * "the bot handed this to me" has to stop the NEXT message starting a new flow as
 * well, or a host mid-conversation is interrupted by their own robot. Cleared by the
 * host from the inbox, which is the only place that knows they are finished.
 */
ALTER TABLE crm_contacts ADD COLUMN IF NOT EXISTS bot_paused_at timestamptz;

/* Which bot said this, for the messages a bot sent.
 *
 * NULL for everything else, which is most rows. A host reading a conversation they
 * have just been handed needs to know which half of it they did not write — and
 * after a handoff that is the whole point of reading it.
 */
ALTER TABLE crm_messages ADD COLUMN IF NOT EXISTS bot_id uuid
    REFERENCES crm_bots(id) ON DELETE SET NULL;
