// Package media stores recorded session files.
//
// Behind an interface with one implementation, deliberately. Recordings are the
// one thing in this system that will not fit on the API's disk forever, so the
// day it moves to S3 is a new type in this package and a line in Load — not a
// change to any handler. The interface is shaped for that move: append-only
// writes, a read that supports range requests, and opaque keys.
package media

import (
	"context"
	"errors"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"
)

// Store is the seam. Keys are opaque, generated by the caller, and must never be
// taken from user input — Disk resolves them under a root and refuses anything
// that tries to climb out, but a caller that passes a filename from a form is
// asking for trouble in every backend.
type Store interface {
	// Append adds bytes to the end of the object, creating it if it does not
	// exist, and reports the object's total size afterwards. Append rather than
	// Write because a recording arrives in chunks over its whole duration, and
	// buffering an hour of video in memory is not an option.
	Append(ctx context.Context, key string, r io.Reader) (int64, error)
	// Open returns a reader positioned at the start, plus the object's size.
	// ReadSeekCloser so an HTTP handler can serve range requests — without
	// seeking, a browser cannot scrub a video, it can only play it from 0.
	Open(ctx context.Context, key string) (io.ReadSeekCloser, int64, error)
	Delete(ctx context.Context, key string) error
	/* Finalize marks an object done — every Append call for this key has
	 * already happened, and nothing will call Append on it again.
	 *
	 * A no-op for Disk: every Append already fsyncs before returning, so an
	 * object built one Append at a time is durable the moment the last one
	 * lands, and there is nothing left to do. It exists on the interface at
	 * all because a backend that cannot append to a remote object in place
	 * (S3, and B2 through its S3-compatible API) has to stage the bytes
	 * somewhere local and push the finished object in one upload — see S3
	 * in this package — and needs to be told when that moment has arrived.
	 * The handler that calls Complete on a recording is the only caller;
	 * see handleCompleteRecording. */
	Finalize(ctx context.Context, key string) error
	FinalizeWithProgress(ctx context.Context, key string, onProgress func(percent int)) error
	// Describe names the backend for logs and the readiness endpoint.
	Describe() string
}

var (
	ErrNotFound = errors.New("no such object")
	ErrBadKey   = errors.New("unsafe storage key")
)

// Disk keeps objects as files under a root directory.
type Disk struct {
	root string
}

// NewDisk prepares the root directory. It writes and removes a probe file so a
// permissions problem is a startup error rather than a recording that silently
// captures nothing for forty minutes.
func NewDisk(root string) (*Disk, error) {
	if strings.TrimSpace(root) == "" {
		return nil, errors.New("recordings directory is empty")
	}
	abs, err := filepath.Abs(root)
	if err != nil {
		return nil, err
	}
	if err := os.MkdirAll(abs, 0o750); err != nil {
		return nil, fmt.Errorf("create %s: %w", abs, err)
	}
	probe := filepath.Join(abs, ".writable")
	if err := os.WriteFile(probe, []byte("ok"), 0o640); err != nil {
		return nil, fmt.Errorf("%s is not writable: %w", abs, err)
	}
	if err := os.Remove(probe); err != nil {
		return nil, fmt.Errorf("%s is not writable: %w", abs, err)
	}
	return &Disk{root: abs}, nil
}

func (d *Disk) Describe() string { return "disk:" + d.root }

// path resolves a key under the root, refusing anything that escapes it.
//
// Belt and braces: our keys are generated from UUIDs, so this should be
// unreachable. It is here because "the key is always safe" is exactly the
// assumption that stops being true when someone adds a second caller.
func (d *Disk) path(key string) (string, error) {
	// A leading slash does not escape the root — Join would fold it into
	// root/etc/passwd — but it is not a key this package ever generates, and
	// silently reinterpreting it as a nested path is how a caller ends up writing
	// somewhere they did not mean to.
	if key == "" || strings.HasPrefix(key, "/") ||
		strings.ContainsAny(key, `\:`) || strings.Contains(key, "..") {
		return "", ErrBadKey
	}
	full := filepath.Join(d.root, filepath.FromSlash(key))
	if !strings.HasPrefix(full, d.root+string(os.PathSeparator)) {
		return "", ErrBadKey
	}
	return full, nil
}

func (d *Disk) Append(_ context.Context, key string, r io.Reader) (int64, error) {
	full, err := d.path(key)
	if err != nil {
		return 0, err
	}
	if err := os.MkdirAll(filepath.Dir(full), 0o750); err != nil {
		return 0, err
	}
	f, err := os.OpenFile(full, os.O_CREATE|os.O_WRONLY|os.O_APPEND, 0o640)
	if err != nil {
		return 0, err
	}
	defer f.Close()

	if _, err := io.Copy(f, r); err != nil {
		return 0, err
	}
	// Sync before reporting success. A recording is not reproducible, so the
	// cost of an fsync per chunk is worth paying: a machine that loses power
	// mid-webinar should lose the last few seconds, not the file.
	if err := f.Sync(); err != nil {
		return 0, err
	}
	info, err := f.Stat()
	if err != nil {
		return 0, err
	}
	return info.Size(), nil
}

func (d *Disk) Open(_ context.Context, key string) (io.ReadSeekCloser, int64, error) {
	full, err := d.path(key)
	if err != nil {
		return nil, 0, err
	}
	f, err := os.Open(full)
	if err != nil {
		if os.IsNotExist(err) {
			return nil, 0, ErrNotFound
		}
		return nil, 0, err
	}
	info, err := f.Stat()
	if err != nil {
		f.Close()
		return nil, 0, err
	}
	return f, info.Size(), nil
}

func (d *Disk) Delete(_ context.Context, key string) error {
	full, err := d.path(key)
	if err != nil {
		return err
	}
	if err := os.Remove(full); err != nil && !os.IsNotExist(err) {
		return err
	}
	return nil
}

// Finalize is a no-op — see the interface's own doc comment for why.
func (d *Disk) Finalize(_ context.Context, _ string) error { return nil }

func (d *Disk) FinalizeWithProgress(_ context.Context, _ string, onProgress func(percent int)) error {
	if onProgress != nil {
		onProgress(100)
	}
	return nil
}
